# Generated by Django 3.0.3 on 2020-05-28 00:21

import DetectionApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRegulation',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('cg_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'category_regulation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemdetectionSHistory',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=DetectionApp.models.date_upload_detection)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'itemDetection_s_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'point_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=DetectionApp.models.date_upload_detection)),
            ],
            options={
                'db_table': 'itemdetectionApp_upload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WasteCategoryL',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('cg_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'waste_category_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WasteCategoryM',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('cg_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'waste_category_m',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WasteCategoryS',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('cg_name', models.CharField(max_length=45)),
                ('label_name', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'db_table': 'waste_category_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Upload_Clean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=DetectionApp.models.date_upload_clean)),
            ],
            options={
                'db_table': 'itemdetectionApp_upload_clean',
            },
        ),
    ]
