# Generated by Django 3.0.3 on 2020-05-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReceiver',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'message_receiver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessageSender',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('recv_chk', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'message_sender',
                'managed': False,
            },
        ),
    ]
