# Generated by Django 3.0.3 on 2020-05-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_auto_20200512_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationwasteinformation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
