# Generated by Django 3.0.3 on 2020-05-28 00:21

import CommunityApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('share_complete', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=CommunityApp.models.date_upload_community)),
            ],
            options={
                'db_table': 'community',
                'managed': False,
            },
        ),
    ]
