# Generated by Django 3.0.3 on 2020-05-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeasureApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'managed': False},
        ),
    ]
