# Generated by Django 3.0.3 on 2020-05-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeasureApp', '0002_auto_20200528_0021'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='upload',
            table=None,
        ),
    ]
