# Generated by Django 3.0.3 on 2020-05-29 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeasureApp', '0003_auto_20200529_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={},
        ),
    ]
