# Generated by Django 3.0.3 on 2020-05-30 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeasureApp', '0005_auto_20200530_0201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='upload',
            table='measure_upload',
        ),
    ]
