# Generated by Django 3.0.3 on 2020-05-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeTips',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('item_corresponding', models.CharField(blank=True, max_length=45, null=True)),
                ('item_discorresponding', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'discharge_tips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WasteCategoryL',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('cg_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'waste_category_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WasteCategoryM',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('cg_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'waste_category_m',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WasteCategoryS',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('cg_name', models.CharField(max_length=45)),
                ('label_name', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'db_table': 'waste_category_s',
                'managed': False,
            },
        ),
    ]
